services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: user
      MINIO_ROOT_PASSWORD: password
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - /Users/chriskingsborough/Documents/repos/football/data:/data
    command: server /data --console-address ":9001"